### ISSUE TITLE
Text fontSize style issue

### ISSUE THREAD

**Issue by buhe** [ptmt/react-native-desktop#86]
Awesome Project!
Here is my code.
```
<View style={{width:80,height:80}}><Text style={{marginTop:50,fontSize:60}}>35</Text></View>
```
Text has been truncate.
![image](https://cloud.githubusercontent.com/assets/650753/15626457/e2243308-24f7-11e6-8ed9-569daaf5328f.png)

I change fontSize to 20 , Everything is ok .

![image](https://cloud.githubusercontent.com/assets/650753/15626478/3cd01c40-24f8-11e6-9385-f5086aab1677.png)

**Comment by buhe** [comment]
```
<Text style={{fontSize:60}}>35</Text>
```
Simple code does't work.

**Comment by nunobbras** [comment]
You can solve this adding some top padding (and some height). Playing with the padding is clearly a workaround, but it works.
```
                  <View style={{width:80,height:100}}>
                    <Text style={{marginTop:50, fontSize:60, paddingTop:40}}>35</Text>
                  </View>                  
```

**Comment by ptmt** [comment]
Sorry for not answering, I was out of the grid for a couple days. Thank you for posting the issue, I fixed this in the latest release (0.8.5).
The problem was related to `overflow` property which wasn't set correctly by default. See UIExample for more details of usage `overflow: hidden`:
![image](https://cloud.githubusercontent.com/assets/1004115/15657256/e6295c6e-26b7-11e6-9b27-ac0eb6fa4666.png)

**Comment by buhe** [comment]
👍

**Comment by buhe** [comment]
I try add 
```
<View style={{overflow: 'visible'}}><Text style={{overflow: 'visible',fontSize:60}}>35</Text></View>
```
to View and Text tags , But the problem is still unsolved.

I try @nunobbras 's solution to solve it .

**Comment by ptmt** [comment]
Have you updated the version of react-native-desktop? The problem should be fixed without any workaround. Please, create the repo that reproduce the issue, it latest version doesn't work for you.
